import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        performance: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        Worker: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLVideoElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        WebGLRenderingContext: 'readonly',
        MediaRecorder: 'readonly',
        AudioContext: 'readonly',
        OscillatorNode: 'readonly',
        GainNode: 'readonly',
        DeviceOrientationEvent: 'readonly',
        DeviceMotionEvent: 'readonly',
        PointerEvent: 'readonly',
        TouchEvent: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        crypto: 'readonly',
        Uint8Array: 'readonly',
        Uint32Array: 'readonly',
        Float32Array: 'readonly',
        ArrayBuffer: 'readonly',
        DataView: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Symbol: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        Error: 'readonly',
        TypeError: 'readonly',
        RangeError: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        encodeURIComponent: 'readonly',
        decodeURIComponent: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        structuredClone: 'readonly',
        queueMicrotask: 'readonly',
        postMessage: 'readonly',
        self: 'readonly',
        globalThis: 'readonly',
        // Media/Recording APIs
        MediaStream: 'readonly',
        MediaStreamTrack: 'readonly',
        MediaRecorder: 'readonly',
        VideoEncoder: 'readonly',
        VideoDecoder: 'readonly',
        VideoFrame: 'readonly',
        AudioEncoder: 'readonly',
        EncodedVideoChunk: 'readonly',
        // Web APIs
        File: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        // DOM globals
        prompt: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        history: 'readonly',
        location: 'readonly',
        screen: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        OffscreenCanvas: 'readonly',
        Path2D: 'readonly',
        DOMParser: 'readonly',
        XMLHttpRequest: 'readonly',
        WebSocket: 'readonly',
        EventTarget: 'readonly',
        IDBKeyRange: 'readonly',
        indexedDB: 'readonly',
        caches: 'readonly',
        ServiceWorkerRegistration: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-debugger': 'warn',
    },
  },
];
